name: pro_image_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 4.3.6
homepage: https://github.com/hm21/pro_image_editor/
repository: https://github.com/hm21/pro_image_editor/
issue_tracker: https://github.com/hm21/pro_image_editor/issues/
documentation: https://github.com/hm21/pro_image_editor/


topics:
  - image-editor
  - image
  - editor
  - widget
  - painting

screenshots:
  - description: "Showcase from the image editor with the frosted-glass design"
    path: assets/showcase-frosted-glass.jpg
  - description: "Showcase from the image editor with the Whatsapp design"
    path: assets/showcase-whatsapp.jpg
  - description: "Showcase from the image editor with simple design"
    path: assets/showcase.jpg

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  emoji_picker_flutter: ^2.2.0
  http: ^1.2.1
  image: ^4.2.0
  vibration: ^1.9.0
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  network_image_mock: ^2.0.0

flutter:
  assets:
    - lib/web/web_worker.dart.js
    - lib/web/web_worker.dart.js.deps
    - lib/web/web_worker.dart.js.map
  fonts:
   - family: ProImageEditorIcons
     fonts:
      - asset: lib/fonts/ProImageEditorIcons.ttf