name: pro_image_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 2.7.11
homepage: https://github.com/hm21/pro_image_editor/
repository: https://github.com/hm21/pro_image_editor/
issue_tracker: https://github.com/hm21/pro_image_editor/issues/
documentation: https://github.com/hm21/pro_image_editor/


topics:
  - image-editor
  - image
  - editor
  - widget
  - painting

screenshots:
  - description: "Showcase from the image editor with the Whatsapp design"
    path: assets/showcase-whatsapp.png
  - description: "Showcase from the image editor with simple design"
    path: assets/showcase.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_editor: ^1.4.0
  extended_image: ^8.2.0
  rounded_background_text: ^0.5.0
  colorfilter_generator: ^0.0.8
  screenshot: ^3.0.0
  vibration: ^1.8.4
  http: ^1.2.1
  emoji_picker_flutter: ^2.2.0
  image: ^4.1.7
  defer_pointer: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  network_image_mock: ^2.0.0
  build_runner: ^2.4.9

flutter:
  fonts:
   - family: ProImageEditorIcons
     fonts:
      - asset: lib/fonts/ProImageEditorIcons.ttf